"""dump_schema.py — generate the portable FRAN schema (schema/fran_schema.sql) from a live corpus DB.

WHY THIS EXISTS: FRAN could not be installed by anyone else. Nothing in the repo created the six core
tables — `corpus_ingest.py` cites `scripts/migrate_pg_v1.sql`, which has never existed here — so a new
institution had install instructions leading to a database with no tables. This regenerates the schema
from a working instance, so the bootstrap can never drift from reality the way a hand-maintained .sql
file does.

    python scripts/dump_schema.py                    # -> schema/fran_schema.sql
    python scripts/dump_schema.py --out other.sql

Emission order matters and is deliberate: every CREATE TABLE first, then foreign keys as ALTER
statements, then indexes. That way the file applies cleanly regardless of dependency order between
tables, which a naive per-table dump gets wrong as soon as two tables reference each other.

SITE-SPECIFIC TABLES ARE EXCLUDED (see EXCLUDE): the UC Davis LIMS mirrors, the internal curation
tables and the multi-agent coordination bus are ours, not part of what FRAN *is*. Everything else is
included, so a new field added to a core table is picked up automatically on the next regeneration.
"""
from __future__ import annotations
import argparse, os, sys

# corpus_ingest supplies the connection helper. In a repo checkout it lives in ../ingest; on the
# Hive working copy the scripts sit side by side. Try both rather than assume a layout.
_here = os.path.dirname(os.path.abspath(__file__))
for _cand in (os.path.join(_here, "..", "ingest"), _here, os.getcwd()):
    if os.path.exists(os.path.join(_cand, "corpus_ingest.py")):
        sys.path.insert(0, _cand)
        break

# Tables that belong to THIS deployment rather than to FRAN. Excluded from the portable schema.
EXCLUDE = {
    # UC Davis LIMS mirrors and service-folder tracking
    "coreomics_samples_cache", "coreomics_submissions_cache", "delimp_submission_service_dir",
    # local curation of customer/PI naming
    "delimp_pi_profile", "delimp_lab_institute_override",
    # internal mirrors of the public tables
    "delimp_searches_internal", "delimp_raw_files_internal",
    # operational worklists / logs, meaningless in a fresh instance
    "delimp_search_step_logs", "delimp_spectrum_regen_queue", "delimp_peptide_consensus_done",
    # the multi-Claude coordination bus (ours, not FRAN's)
    "delimp_claude_heartbeat", "delimp_claude_messages",
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                                  "..", "schema", "fran_schema.sql"))
    a = ap.parse_args()
    import corpus_ingest as ci
    conn = ci._conn(); cur = conn.cursor()
    cur.execute("set statement_timeout='300s'")

    cur.execute("""select c.relname, c.relkind from pg_class c join pg_namespace n on n.oid=c.relnamespace
                   where n.nspname='public' and c.relkind in ('r','m','v') order by c.relkind, c.relname""")
    rels = [(r[0], r[1]) for r in cur.fetchall() if r[0] not in EXCLUDE]
    tables = [r for r, k in rels if k == "r"]
    views  = [(r, k) for r, k in rels if k in ("m", "v")]

    out = ["-- FRAN corpus schema — GENERATED by scripts/dump_schema.py. Do not hand-edit.",
           "-- Apply to an empty database:  psql \"$FRAN_DB_URL\" -f schema/fran_schema.sql",
           f"-- tables: {len(tables)}   views/matviews: {len(views)}", ""]

    # 1) tables (columns + defaults + NOT NULL only; constraints come later so order never matters)
    for t in tables:
        cur.execute("""select a.attname, format_type(a.atttypid, a.atttypmod), a.attnotnull,
                              pg_get_expr(d.adbin, d.adrelid)
                       from pg_attribute a
                       left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum
                       where a.attrelid=%s::regclass and a.attnum>0 and not a.attisdropped
                       order by a.attnum""", (t,))
        # serial/bigserial columns appear in the catalog as plain integer types carrying a
        # nextval() default; the SEQUENCE itself is a separate object. Emitting the default verbatim
        # produces SQL that fails on an empty database with
        # 'relation "<table>_<col>_seq" does not exist'. Re-fold them into the serial pseudo-types,
        # which recreate the sequence, the default and the ownership in one go. (Caught by the
        # container install test; a hand-written schema would have shipped broken.)
        SERIAL = {"bigint": "bigserial", "integer": "serial", "smallint": "smallserial"}
        cols = []
        for name, typ, notnull, default in cur.fetchall():
            if default and default.startswith("nextval(") and typ in SERIAL:
                cols.append(f'    "{name}" {SERIAL[typ]}')      # NOT NULL is implied by serial
                continue
            piece = f'    "{name}" {typ}'
            if default is not None:
                piece += f" DEFAULT {default}"
            if notnull:
                piece += " NOT NULL"
            cols.append(piece)
        out.append(f"CREATE TABLE IF NOT EXISTS {t} (\n" + ",\n".join(cols) + "\n);\n")

    # 2) constraints. PK/UNIQUE/CHECK first, then FKs — a FK cannot be added before the key it
    #    references exists, and referencing tables are not guaranteed to sort after referenced ones.
    pk_uni, fks = [], []
    for t in tables:
        cur.execute("""select conname, contype, pg_get_constraintdef(oid)
                       from pg_constraint where conrelid=%s::regclass order by contype""", (t,))
        for name, ctype, cdef in cur.fetchall():
            stmt = (f"ALTER TABLE {t} ADD CONSTRAINT {name} {cdef};")
            if ctype == b"f" or ctype == "f":
                fks.append(stmt)
            else:
                pk_uni.append(stmt)
    out.append("-- primary keys, unique and check constraints")
    out += pk_uni + [""]

    # 3) views and matviews (after tables, before FKs is fine; they only read)
    if views:
        # Views can build on OTHER views: delimp_mv_species_proteins feeds another matview, and
        # emitting them in name order put the dependent first ->
        # 'relation "delimp_mv_species_proteins" does not exist'. Sort by actual dependency.
        # (Caught by the container install test, not by reading the file.)
        cur.execute("""select distinct dep.relname, ref.relname
                       from pg_depend d
                       join pg_rewrite r on r.oid = d.objid
                       join pg_class dep on dep.oid = r.ev_class
                       join pg_class ref on ref.oid = d.refobjid
                       join pg_namespace n on n.oid = ref.relnamespace
                       where d.classid = 'pg_rewrite'::regclass
                         and d.refclassid = 'pg_class'::regclass
                         and dep.oid <> ref.oid and n.nspname = 'public'
                         and ref.relkind in ('r','m','v')""")
        vnames = {v for v, _ in views}
        needs = {v: set() for v in vnames}
        for dep, ref in cur.fetchall():
            if dep in vnames and ref in vnames:
                needs[dep].add(ref)
        ordered, placed = [], set()
        while len(placed) < len(views):
            progress = False
            for v, kind in views:
                if v not in placed and needs[v] <= placed:
                    ordered.append((v, kind)); placed.add(v); progress = True
            if not progress:      # a cycle would loop forever; emit the rest and say so
                rest = [(v, k) for v, k in views if v not in placed]
                print(f"  WARNING: dependency cycle among views {[v for v,_ in rest]}; "
                      f"emitting in name order", file=sys.stderr)
                ordered += rest
                break
        views = ordered
        out.append("-- views / materialized views, in dependency order (refresh after first ingest)")
        for v, kind in views:
            cur.execute("select pg_get_viewdef(%s::regclass, true)", (v,))
            body = cur.fetchone()[0].rstrip().rstrip(";")
            # PostgreSQL accepts CREATE MATERIALIZED VIEW IF NOT EXISTS but NOT
            # CREATE VIEW IF NOT EXISTS -- the plain-view form is a syntax error. Use OR REPLACE
            # there, which is the idempotent spelling for views.
            if kind == "m":
                out.append(f"CREATE MATERIALIZED VIEW IF NOT EXISTS {v} AS\n{body} WITH NO DATA;\n")
            else:
                out.append(f"CREATE OR REPLACE VIEW {v} AS\n{body};\n")

    out.append("-- foreign keys (added last so table creation order is irrelevant)")
    out += fks + [""]

    # 4) indexes, excluding those PostgreSQL already created for the constraints above
    out.append("-- indexes")
    for t in tables:
        cur.execute("""select indexdef from pg_indexes where schemaname='public' and tablename=%s
                       and indexname not in (select conname from pg_constraint where conrelid=%s::regclass)
                       order by indexname""", (t, t))
        for (d,) in cur.fetchall():
            out.append(d.replace("CREATE INDEX ", "CREATE INDEX IF NOT EXISTS ", 1)
                        .replace("CREATE UNIQUE INDEX ", "CREATE UNIQUE INDEX IF NOT EXISTS ", 1) + ";")
    out.append("")

    # 5) seed rows the schema itself depends on. delimp_precursors has a FK to
    #    delimp_schema_version(version) and corpus_ingest stamps every row with SCHEMA_VERSION, so a
    #    fresh database rejects the very first ingest unless this row exists.
    cur.execute("select version from delimp_schema_version order by version")
    vers = [r[0] for r in cur.fetchall()]
    if vers:
        out.append("-- seed: delimp_precursors.ingested_schema_version references this table, so the")
        out.append("-- first ingest FAILS on an empty one. Keep in step with ingest/versions.py.")
        for v in vers:
            out.append(f"INSERT INTO delimp_schema_version (version) VALUES ('{v}') "
                       f"ON CONFLICT DO NOTHING;")
        out.append("")

    # Matviews must be REFRESHED in dependency order too, not just created in it: refreshing one
    # that reads an as-yet-unpopulated matview fails with "materialized view has not been
    # populated". Emit the order so an operator does not have to rediscover it.
    mvs = [v for v, k in views if k == "m"]
    if mvs:
        out.append("-- REFRESH ORDER (matviews depend on each other; refreshing out of order fails")
        out.append("-- with 'materialized view has not been populated'). After your first ingest:")
        for v in mvs:
            out.append(f"--   REFRESH MATERIALIZED VIEW {v};")
        out.append("")

    path = os.path.abspath(a.out)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write("\n".join(out))
    print(f"wrote {path}")
    print(f"  {len(tables)} tables, {len(views)} views/matviews, {len(pk_uni)} keys, {len(fks)} FKs")
    print(f"  excluded as site-specific: {', '.join(sorted(EXCLUDE))}")


if __name__ == "__main__":
    main()
